server:
  port: 8080
  tomcat:
    max-connections: 5000
    accept-count: 50
    connection-timeout: 5s

spring:
  application:
    name: urlshortener
  threads:
    virtual:
      enabled: true # <- Магия Java 21 здесь. Все @Async и Tomcat-запросы станут виртуальными потоками

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shortener}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 2000
      idle-timeout: 300000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2s            # таймаут на операцию (чтение/запись)

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jvm.gc.pause: true

app:
  link-ttl-days: 7
  extend-threshold-minutes: 60
  cleanup-interval-ms: 3600000

logging:
  level:
    ru.bmstu.dzhioev.urlshortener: INFO
