global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shortener-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'redis-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['redis-exporter:9121']